apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-tls
  namespace: ingress-nginx
spec:
  commonName: nginx
  usages:
    - server auth
  dnsNames:
    - ingress-nginx-controller.ingress-nginx.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  secretName: nginx-tls
  issuerRef:
    name: nginx-selfsigned