apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: kurtis@common.xyz
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-secrets
              key: CLOUDFLARE_API_TOKEN
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-dns
  namespace: cert-manager
spec:
  secretName: wildcard-cert-dns-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.unique.rocks'
  dnsNames:
    - '*.unique.rocks'
    - 'unique.rocks'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
